---
- name: Execute script on F5 BIG-IP
  hosts: bigip_hosts
  gather_facts: no
  tasks:
    - name: Copy the script to the BIG-IP
      ansible.builtin.copy:
        src: mitigation.sh
        dest: /tmp/mitigation.sh
        mode: '0777'
      delegate_to: "{{ inventory_hostname }}"

    - name: Execute the script on the BIG-IP
      ansible.builtin.shell:
        cmd: /tmp/mitigation.sh
      delegate_to: "{{ inventory_hostname }}"
      register: script_result

    - name: Display the script output
      debug:
        msg: "{{ item }}"
      loop: "{{ script_result.stdout.split('\n') }}"
      when: script_result.stdout

    - name: Display the script error output
      debug:
        msg: "{{ item }}"
      loop: "{{ script_result.stderr.split('\n') }}"
      when: script_result.stderr

    - name: Remove the script from the BIG-IP
      ansible.builtin.file:
        path: /tmp/mitigation.sh
        state: absent
      delegate_to: "{{ inventory_hostname }}"
